#!/usr/bin/env python3
"""
Issue Generator Agent
Ensures minimum number of open issues by generating new ones with Claude AI
"""

import os
import sys
import json
from github import Github, Auth
from anthropic import Anthropic

# Configuration
MIN_ISSUES = int(os.getenv('MIN_OPEN_ISSUES', '3'))
GITHUB_TOKEN = os.getenv('GITHUB_TOKEN')
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY')
REPO_NAME = os.getenv('REPO_NAME')

print(f"🔍 Checking issue count (minimum: {MIN_ISSUES})")

# Initialize GitHub client
auth = Auth.Token(GITHUB_TOKEN)
gh = Github(auth=auth)
repo = gh.get_repo(REPO_NAME)

# Count open issues (excluding pull requests)
open_issues = list(repo.get_issues(state='open'))
open_issues = [i for i in open_issues if not i.pull_request]
issue_count = len(open_issues)

print(f"📊 Current open issues: {issue_count}")

if issue_count >= MIN_ISSUES:
    print(f"✅ Sufficient issues exist ({issue_count} >= {MIN_ISSUES})")
    sys.exit(0)

# Need to generate issues
needed = MIN_ISSUES - issue_count
print(f"🤖 Generating {needed} new issue(s)...")

# Initialize Claude
anthropic = Anthropic(api_key=ANTHROPIC_API_KEY)

# Get repository context
print("📖 Analyzing repository for potential issues...")

try:
    readme = repo.get_readme().decoded_content.decode('utf-8')[:1000]
except:
    readme = "No README found"

recent_commits = list(repo.get_commits()[:5])
commit_messages = "\n".join([f"- {c.commit.message.split(chr(10))[0]}" for c in recent_commits])

# Build prompt for Claude
prompt = f"""You are analyzing a GitHub repository to suggest issues.

Repository: {REPO_NAME}

README excerpt:
{readme}

Recent commits:
{commit_messages}

Current open issues:
{chr(10).join([f"- #{i.number}: {i.title}" for i in open_issues[:10]])}

Task: Generate {needed} new issue(s) for this repository. Prioritize:
1. Bug fixes (if you can identify potential bugs from the code/docs)
2. Feature enhancements (if no bugs found)
3. Documentation improvements
4. Code quality improvements

For each issue, provide:
- Title (clear and concise, max 80 chars)
- Description (brief, max 200 chars)
- Labels (choose from: bug, enhancement, documentation, good first issue)

Respond ONLY with valid JSON, no markdown formatting:
{{
  "issues": [
    {{
      "title": "Issue title",
      "body": "Brief description",
      "labels": ["bug"]
    }}
  ]
}}

IMPORTANT: Keep descriptions brief. Output ONLY the JSON object, nothing else."""

# Call Claude
message = anthropic.messages.create(
    model="claude-sonnet-4-5",
    max_tokens=4096,
    messages=[{"role": "user", "content": prompt}]
)

response_text = message.content[0].text
print(f"🤖 Claude response received")

# Parse response
try:
    # Clean up response - remove markdown code blocks if present
    cleaned_response = response_text.strip()
    if "```json" in cleaned_response:
        cleaned_response = cleaned_response.split("```json")[1].split("```")[0].strip()
    elif "```" in cleaned_response:
        cleaned_response = cleaned_response.split("```")[1].split("```")[0].strip()
    
    # Find JSON object in response
    start_idx = cleaned_response.find('{')
    end_idx = cleaned_response.rfind('}') + 1
    
    if start_idx == -1 or end_idx == 0:
        raise ValueError("No JSON object found in response")
    
    json_str = cleaned_response[start_idx:end_idx]
    data = json.loads(json_str)
    issues_to_create = data.get('issues', [])[:needed]
    
    if not issues_to_create:
        print("⚠️  No issues generated by Claude")
        sys.exit(0)
    
    # Create issues
    for issue_data in issues_to_create:
        title = issue_data.get('title', 'Untitled Issue')[:80]  # Limit title length
        body = issue_data.get('body', '')
        labels = issue_data.get('labels', [])
        
        full_body = f"{body}\n\n---\n*Generated by Issue Generator Agent*"
        
        new_issue = repo.create_issue(
            title=title,
            body=full_body,
            labels=labels
        )
        
        print(f"✅ Created issue #{new_issue.number}: {title}")
    
    print(f"🎉 Successfully generated {len(issues_to_create)} issue(s)")
    
except json.JSONDecodeError as e:
    print(f"❌ Failed to parse Claude response as JSON: {e}")
    print(f"Response (first 1000 chars): {response_text[:1000]}")
    print(f"Response (last 500 chars): {response_text[-500:]}")
    sys.exit(1)
except Exception as e:
    print(f"❌ Error creating issues: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)
