#!/usr/bin/env python3
"""
Issue Generator Agent
Ensures minimum number of open issues by generating new ones with Claude AI
"""

import os
import sys
import json
from github import Github
from anthropic import Anthropic

# Configuration
MIN_ISSUES = int(os.getenv('MIN_OPEN_ISSUES', '3'))
GITHUB_TOKEN = os.getenv('GITHUB_TOKEN')
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY')
REPO_NAME = os.getenv('REPO_NAME')

print(f"🔍 Checking issue count (minimum: {MIN_ISSUES})")

# Initialize GitHub client
gh = Github(GITHUB_TOKEN)
repo = gh.get_repo(REPO_NAME)

# Count open issues (excluding pull requests)
open_issues = list(repo.get_issues(state='open'))
open_issues = [i for i in open_issues if not i.pull_request]
issue_count = len(open_issues)

print(f"📊 Current open issues: {issue_count}")

if issue_count >= MIN_ISSUES:
    print(f"✅ Sufficient issues exist ({issue_count} >= {MIN_ISSUES})")
    sys.exit(0)

# Need to generate issues
needed = MIN_ISSUES - issue_count
print(f"🤖 Generating {needed} new issue(s)...")

# Initialize Claude
anthropic = Anthropic(api_key=ANTHROPIC_API_KEY)

# Get repository context
print("📖 Analyzing repository for potential issues...")

try:
    readme = repo.get_readme().decoded_content.decode('utf-8')[:1000]
except:
    readme = "No README found"

recent_commits = list(repo.get_commits()[:5])
commit_messages = "\n".join([f"- {c.commit.message.split(chr(10))[0]}" for c in recent_commits])

# Build prompt for Claude
prompt = f"""You are analyzing a GitHub repository to suggest issues.

Repository: {REPO_NAME}

README excerpt:
{readme}

Recent commits:
{commit_messages}

Current open issues:
{chr(10).join([f"- #{i.number}: {i.title}" for i in open_issues[:10]])}

Task: Generate {needed} new issue(s) for this repository. Prioritize:
1. Bug fixes (if you can identify potential bugs from the code/docs)
2. Feature enhancements (if no bugs found)
3. Documentation improvements
4. Code quality improvements

For each issue, provide:
- Title (clear and concise)
- Description (detailed with context)
- Labels (choose from: bug, enhancement, documentation, good first issue)

Respond in JSON format:
{{
  "issues": [
    {{
      "title": "Issue title",
      "body": "Detailed description",
      "labels": ["bug"]
    }}
  ]
}}

IMPORTANT: Only suggest realistic, actionable issues."""

# Call Claude
message = anthropic.messages.create(
    model="claude-3-5-sonnet-20240620",
    max_tokens=2048,
    messages=[{"role": "user", "content": prompt}]
)

response_text = message.content[0].text
print(f"🤖 Claude response received")

# Parse response
try:
    if "```json" in response_text:
        response_text = response_text.split("```json")[1].split("```")[0].strip()
    elif "```" in response_text:
        response_text = response_text.split("```")[1].split("```")[0].strip()
    
    data = json.loads(response_text)
    issues_to_create = data.get('issues', [])[:needed]
    
    # Create issues
    for issue_data in issues_to_create:
        title = issue_data.get('title', 'Untitled Issue')
        body = issue_data.get('body', '')
        labels = issue_data.get('labels', [])
        
        full_body = f"{body}\n\n---\n*Generated by Issue Generator Agent*"
        
        new_issue = repo.create_issue(
            title=title,
            body=full_body,
            labels=labels
        )
        
        print(f"✅ Created issue #{new_issue.number}: {title}")
    
    print(f"🎉 Successfully generated {len(issues_to_create)} issue(s)")
    
except json.JSONDecodeError as e:
    print(f"❌ Failed to parse Claude response as JSON: {e}")
    print(f"Response: {response_text[:500]}")
    sys.exit(1)
except Exception as e:
    print(f"❌ Error creating issues: {e}")
    sys.exit(1)
